In [1]:
32+766

798

This is my first python code just as a sample 
Starting with # is the comment


In [10]:
from numpy import *
import time
def trade_version ():
    tl = time.time()
    x = range(10000000)
    y = range(10000000)
    z = []
    for i in range (len (x)):
        z.append(x[i]+y[i])
    return time.time()-tl
trade_version()

7.194702386856079

In [15]:
def numpy_version():
    tl = time.time()
    x = arange(100000000)
    y = arange(100000000)
    z = x+y
    return time.time() - tl
numpy_version()

1.0486509799957275

In [18]:
import numpy as np
a = np.array([1,2,3])

In [27]:
import numpy as np
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float )
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.ones((2,3,4), dtype = np.int16)

In [30]:
d = np.arange(10,25,6)

In [31]:
d

array([10, 16, 22])

In [33]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [34]:
e = np.full((2,2),7)

In [35]:
e

array([[7, 7],
       [7, 7]])

In [38]:
f = np.eye(5)

In [39]:
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.random.random((2,2))

array([[0.27703178, 0.8301129 ],
       [0.95919621, 0.94583291]])

In [46]:
a.shape

(3,)